[workspace]
members = ["swiftide-docker*"]
resolver = "2"

[workspace.dependencies]
tonic = { version = "0.14" }
prost = "0.14"
bytes = "1"
tonic-prost-build = "0.14"
tonic-prost = "0.14"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
swiftide-core = "0.32"
swiftide-indexing = "0.32"
futures-util = "0.3"
async-stream = "0.3"

[workspace.package]
description = "A docker executor for swiftide agent tools"
license = "MIT"
readme = "README.md"
keywords = ["llm", "rag", "ai", "data", "openai"]
homepage = "https://github.com/bosun-ai/swiftide"
repository = "https://github.com/bosun-ai/swiftide-docker-executor"
edition = "2024"
build = "build.rs"
version = "0.13.7"
categories = ["asynchronous"]

[patch.crates-io]
swiftide-core = { git = "https://github.com/bosun-ai/swiftide", package = "swiftide-core", rev = "7a829e171cc0e256ed38e3965d89750b03a9b156" }
swiftide-indexing = { git = "https://github.com/bosun-ai/swiftide", package = "swiftide-indexing", rev = "7a829e171cc0e256ed38e3965d89750b03a9b156" }
swiftide-agents = { git = "https://github.com/bosun-ai/swiftide", package = "swiftide-agents", rev = "7a829e171cc0e256ed38e3965d89750b03a9b156" }
