name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@just
      - run: just docker-build-service
      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov --tests --all-features --lcov --output-path lcov.info -j 2

      - name: Coveralls
        uses: coverallsapp/github-action@v2
