name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@just
      - run: just docker-build-service
      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov --tests --lcov --output-path lcov.info -j 2

      - name: Coveralls
        uses: coverallsapp/github-action@v2
